runtime: nodejs12
instance_class: B1
basic_scaling:
  max_instances: 3
  idle_timeout: 10m
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
env_variables:
  MONGO_URL: 'mongodb+srv://admin:nVzbhPjcsFgArWXW@cluster0.osnbn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'